from __future__ import annotations


# ---------------------------------------------------------------------------
# Preset definitions — Onset Finder (Step 2)
# ---------------------------------------------------------------------------
PRESETS = {
    "birdsong": {
        "description": "Small passerines with rapid, high-frequency calls",
        "HIGHPASS_CUTOFF_HZ": 500, "ONSET_AMPLITUDE_GATE": 0.08,
        "ONSET_AMPLITUDE_WINDOW_MS": 30, "ONSET_SHARPNESS_GATE": 0.0,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 12,
        "ONSET_CLUSTER_WINDOW_MS": 15, "STABLE_RHYTHM_TOLERANCE": 0.25,
        "ONSET_DELTA": 0.05, "ONSET_HOP_LENGTH": 256,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "percussion": {
        "description": "Human drumming, hand clapping, and struck instruments",
        "HIGHPASS_CUTOFF_HZ": 80, "ONSET_AMPLITUDE_GATE": 0.03,
        "ONSET_AMPLITUDE_WINDOW_MS": 50, "ONSET_SHARPNESS_GATE": 0.10,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 30,
        "ONSET_CLUSTER_WINDOW_MS": 25, "STABLE_RHYTHM_TOLERANCE": 0.25,
        "ONSET_DELTA": 0.07, "ONSET_HOP_LENGTH": 256,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "primate": {
        "description": "Chimpanzee drumming, pant-hoots, and primate calls",
        "HIGHPASS_CUTOFF_HZ": 150, "ONSET_AMPLITUDE_GATE": 0.06,
        "ONSET_AMPLITUDE_WINDOW_MS": 60, "ONSET_SHARPNESS_GATE": 0.15,
        "ONSET_SHARPNESS_WINDOW_MS": 25, "MIN_INTER_ONSET_MS": 40,
        "ONSET_CLUSTER_WINDOW_MS": 30, "STABLE_RHYTHM_TOLERANCE": 0.30,
        "ONSET_DELTA": 0.06, "ONSET_HOP_LENGTH": 256,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "insect": {
        "description": "Stridulations, clicks, and high-frequency insect calls",
        "HIGHPASS_CUTOFF_HZ": 1000, "ONSET_AMPLITUDE_GATE": 0.10,
        "ONSET_AMPLITUDE_WINDOW_MS": 20, "ONSET_SHARPNESS_GATE": 0.0,
        "ONSET_SHARPNESS_WINDOW_MS": 15, "MIN_INTER_ONSET_MS": 10,
        "ONSET_CLUSTER_WINDOW_MS": 10, "STABLE_RHYTHM_TOLERANCE": 0.20,
        "ONSET_DELTA": 0.04, "ONSET_HOP_LENGTH": 128,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "whale / marine mammal": {
        "description": "Whale song, dolphin clicks, and marine mammal calls",
        "HIGHPASS_CUTOFF_HZ": 50, "ONSET_AMPLITUDE_GATE": 0.04,
        "ONSET_AMPLITUDE_WINDOW_MS": 100, "ONSET_SHARPNESS_GATE": 0.0,
        "ONSET_SHARPNESS_WINDOW_MS": 40, "MIN_INTER_ONSET_MS": 80,
        "ONSET_CLUSTER_WINDOW_MS": 50, "STABLE_RHYTHM_TOLERANCE": 0.30,
        "ONSET_DELTA": 0.06, "ONSET_HOP_LENGTH": 512,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 20, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "amphibian": {
        "description": "Frog and toad calls — rhythmic, tonal, mid-frequency",
        "HIGHPASS_CUTOFF_HZ": 300, "ONSET_AMPLITUDE_GATE": 0.05,
        "ONSET_AMPLITUDE_WINDOW_MS": 40, "ONSET_SHARPNESS_GATE": 0.05,
        "ONSET_SHARPNESS_WINDOW_MS": 25, "MIN_INTER_ONSET_MS": 20,
        "ONSET_CLUSTER_WINDOW_MS": 20, "STABLE_RHYTHM_TOLERANCE": 0.25,
        "ONSET_DELTA": 0.06, "ONSET_HOP_LENGTH": 256,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "general / mixed": {
        "description": "Balanced defaults for unknown or varied recordings",
        "HIGHPASS_CUTOFF_HZ": 200, "ONSET_AMPLITUDE_GATE": 0.05,
        "ONSET_AMPLITUDE_WINDOW_MS": 50, "ONSET_SHARPNESS_GATE": 0.05,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 25,
        "ONSET_CLUSTER_WINDOW_MS": 20, "STABLE_RHYTHM_TOLERANCE": 0.25,
        "ONSET_DELTA": 0.06, "ONSET_HOP_LENGTH": 256,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 10, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "ensemble": {
        "description": "Group performance — multiple simultaneous sources (drumming circles, choruses)",
        "HIGHPASS_CUTOFF_HZ": 60, "ONSET_AMPLITUDE_GATE": 0.02,
        "ONSET_AMPLITUDE_WINDOW_MS": 30, "ONSET_SHARPNESS_GATE": 0.0,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 5,
        "ONSET_CLUSTER_WINDOW_MS": 0, "STABLE_RHYTHM_TOLERANCE": 0.35,
        "ONSET_DELTA": 0.04, "ONSET_HOP_LENGTH": 128,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 5, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
    },
    "percussion_sharp_rawAudio": {
        "description": "Sharp percussive hits on RAW (uncleaned) audio — e.g. stone pounding, sakau ceremony. Tuned for noisy backgrounds with singing, speech, and crowd sounds.",
        "HIGHPASS_CUTOFF_HZ": 80, "ONSET_AMPLITUDE_GATE": 0.08,
        "ONSET_AMPLITUDE_WINDOW_MS": 50, "ONSET_SHARPNESS_GATE": 0.15,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 10,
        "ONSET_CLUSTER_WINDOW_MS": 10, "STABLE_RHYTHM_TOLERANCE": 0.30,
        "ONSET_DELTA": 0.07, "ONSET_HOP_LENGTH": 128,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 5, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
        "APPLY_HIGHPASS_FILTER": True,
        "CLUSTER_OVERLAPPING_ONSETS": True,
        "FILTER_STABLE_RHYTHMS": True,
        "HP_SMOOTH_LAMBDA": 100, "HP_THRESHOLD_LAMBDA": 1e8,
        "HP_ENVELOPE_WINDOW_MS": 5, "HP_ENVELOPE_HOP_MS": 1,
    },
    "percussion_sharp_cleanedAudio": {
        "description": "Sharp percussive hits on CLEANED audio (after Audio Editor with HPSS). Lower gates since noise was already removed; maximum timing precision.",
        "HIGHPASS_CUTOFF_HZ": 80, "ONSET_AMPLITUDE_GATE": 0.03,
        "ONSET_AMPLITUDE_WINDOW_MS": 50, "ONSET_SHARPNESS_GATE": 0.05,
        "ONSET_SHARPNESS_WINDOW_MS": 20, "MIN_INTER_ONSET_MS": 10,
        "ONSET_CLUSTER_WINDOW_MS": 8, "STABLE_RHYTHM_TOLERANCE": 0.30,
        "ONSET_DELTA": 0.07, "ONSET_HOP_LENGTH": 128,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 5, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
        "APPLY_HIGHPASS_FILTER": False,
        "CLUSTER_OVERLAPPING_ONSETS": True,
        "FILTER_STABLE_RHYTHMS": True,
        "HP_SMOOTH_LAMBDA": 50, "HP_THRESHOLD_LAMBDA": 5e7,
        "HP_ENVELOPE_WINDOW_MS": 5, "HP_ENVELOPE_HOP_MS": 1,
    },
    "percussion_sharp_rawAudio_2": {
        "description": "Distant sharp percussive hits on RAW audio — performers far from mic, very rapid hits (few ms apart). Extra-sensitive gates & finer hop to catch quiet, closely-spaced impacts buried in crowd noise.",
        "HIGHPASS_CUTOFF_HZ": 60, "ONSET_AMPLITUDE_GATE": 0.03,
        "ONSET_AMPLITUDE_WINDOW_MS": 30, "ONSET_SHARPNESS_GATE": 0.05,
        "ONSET_SHARPNESS_WINDOW_MS": 15, "MIN_INTER_ONSET_MS": 5,
        "ONSET_CLUSTER_WINDOW_MS": 0, "STABLE_RHYTHM_TOLERANCE": 0.35,
        "ONSET_DELTA": 0.04, "ONSET_HOP_LENGTH": 64,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 3, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
        "APPLY_HIGHPASS_FILTER": True,
        "CLUSTER_OVERLAPPING_ONSETS": False,
        "FILTER_STABLE_RHYTHMS": True,
        "HP_SMOOTH_LAMBDA": 50, "HP_THRESHOLD_LAMBDA": 1e7,
        "HP_ENVELOPE_WINDOW_MS": 3, "HP_ENVELOPE_HOP_MS": 1,
    },
    "percussion_sharp_cleanedAudio_2": {
        "description": "Distant sharp percussive hits on CLEANED audio — maximum sensitivity for quiet, closely-spaced impacts after Audio Editor processing.",
        "HIGHPASS_CUTOFF_HZ": 60, "ONSET_AMPLITUDE_GATE": 0.01,
        "ONSET_AMPLITUDE_WINDOW_MS": 25, "ONSET_SHARPNESS_GATE": 0.02,
        "ONSET_SHARPNESS_WINDOW_MS": 15, "MIN_INTER_ONSET_MS": 5,
        "ONSET_CLUSTER_WINDOW_MS": 0, "STABLE_RHYTHM_TOLERANCE": 0.35,
        "ONSET_DELTA": 0.03, "ONSET_HOP_LENGTH": 64,
        "ONSET_BACKTRACK": False, "ONSET_REFINE_ENABLED": True,
        "ONSET_REFINE_WINDOW_MS": 3, "ONSET_REFINE_ENERGY_GATE": 0.0,
        "ONSET_METHOD": "adaptive_hp",
        "APPLY_HIGHPASS_FILTER": False,
        "CLUSTER_OVERLAPPING_ONSETS": False,
        "FILTER_STABLE_RHYTHMS": True,
        "HP_SMOOTH_LAMBDA": 30, "HP_THRESHOLD_LAMBDA": 1e7,
        "HP_ENVELOPE_WINDOW_MS": 3, "HP_ENVELOPE_HOP_MS": 1,
    },
}


# Onset Finder preset reasons — explains *why* each setting was changed
# Keyed by preset name → config key → short explanation
_ONSET_PRESET_REASONS = {
    "birdsong": {
        "HIGHPASS_CUTOFF_HZ": "500 Hz — bird vocalisations sit above this; removes wind and traffic",
        "ONSET_AMPLITUDE_GATE": "0.08 — slightly raised to skip quiet background rustle",
        "ONSET_AMPLITUDE_WINDOW_MS": "30 ms — short window matches brief bird syllables",
        "ONSET_SHARPNESS_GATE": "0.0 — disabled; many bird calls have gradual onsets",
        "MIN_INTER_ONSET_MS": "12 ms — allows detection of rapid trills and note clusters",
        "ONSET_CLUSTER_WINDOW_MS": "15 ms — tight window preserves fast trill structure",
        "STABLE_RHYTHM_TOLERANCE": "0.25 — standard tolerance from Roeske et al.",
        "ONSET_DELTA": "0.05 — sensitive to catch soft notes in complex song",
        "ONSET_HOP_LENGTH": "256 — standard resolution; 5.8 ms at 44.1 kHz",
        "ONSET_METHOD": "adaptive_hp — most robust against outdoor noise",
    },
    "percussion": {
        "HIGHPASS_CUTOFF_HZ": "80 Hz — preserves bass drum and low tom content",
        "ONSET_AMPLITUDE_GATE": "0.03 — low gate; percussive hits are usually loud",
        "ONSET_AMPLITUDE_WINDOW_MS": "50 ms — standard window for drum hits",
        "ONSET_SHARPNESS_GATE": "0.10 — filters gradual swells; drums have sharp attacks",
        "MIN_INTER_ONSET_MS": "30 ms — prevents double-triggering on resonant drum strokes",
        "ONSET_CLUSTER_WINDOW_MS": "25 ms — matches Roeske et al. ensemble clustering",
        "STABLE_RHYTHM_TOLERANCE": "0.25 — standard tolerance from Roeske et al.",
        "ONSET_DELTA": "0.07 — balanced; drums have clear spectral flux peaks",
        "ONSET_METHOD": "adaptive_hp — handles varying dynamics well",
    },
    "primate": {
        "HIGHPASS_CUTOFF_HZ": "150 Hz — pant-hoots and drumming extend into low frequencies",
        "ONSET_AMPLITUDE_GATE": "0.06 — moderate gate for field recordings",
        "ONSET_AMPLITUDE_WINDOW_MS": "60 ms — wider window captures broader attack envelopes",
        "ONSET_SHARPNESS_GATE": "0.15 — moderate; filters slow environmental sounds",
        "MIN_INTER_ONSET_MS": "40 ms — primate buttress drumming has ~50+ ms gaps",
        "ONSET_CLUSTER_WINDOW_MS": "30 ms — slightly wider for reverberant forest environments",
        "STABLE_RHYTHM_TOLERANCE": "0.30 — more lenient; primate rhythms are less precise",
        "ONSET_DELTA": "0.06 — moderate sensitivity",
        "ONSET_METHOD": "adaptive_hp — handles forest ambient noise",
    },
    "insect": {
        "HIGHPASS_CUTOFF_HZ": "1000 Hz — insect sounds are typically above 1 kHz",
        "ONSET_AMPLITUDE_GATE": "0.10 — raised; insect recordings tend to be noisy",
        "ONSET_AMPLITUDE_WINDOW_MS": "20 ms — very short window for rapid clicks/stridulations",
        "ONSET_SHARPNESS_GATE": "0.0 — disabled; some stridulations have gradual onsets",
        "MIN_INTER_ONSET_MS": "10 ms — insects can produce very rapid click trains",
        "ONSET_CLUSTER_WINDOW_MS": "10 ms — tight window for rapid sequences",
        "STABLE_RHYTHM_TOLERANCE": "0.20 — stricter; insect rhythms tend to be very regular",
        "ONSET_DELTA": "0.04 — sensitive to catch quiet stridulations",
        "ONSET_HOP_LENGTH": "128 — finer resolution for very rapid events",
        "ONSET_METHOD": "adaptive_hp — handles cicada chorus and broadband noise",
    },
    "whale / marine mammal": {
        "HIGHPASS_CUTOFF_HZ": "50 Hz — whale songs extend into infrasonic range",
        "ONSET_AMPLITUDE_GATE": "0.04 — low gate; preserves quiet distant calls",
        "ONSET_AMPLITUDE_WINDOW_MS": "100 ms — wide window for drawn-out whale phrases",
        "ONSET_SHARPNESS_GATE": "0.0 — disabled; whale calls have slow, sweeping onsets",
        "MIN_INTER_ONSET_MS": "80 ms — whale call elements are widely spaced",
        "ONSET_CLUSTER_WINDOW_MS": "50 ms — wide window for reverberant underwater acoustics",
        "STABLE_RHYTHM_TOLERANCE": "0.30 — lenient; marine rhythms are irregular",
        "ONSET_DELTA": "0.06 — moderate sensitivity",
        "ONSET_HOP_LENGTH": "512 — coarser resolution matches slow temporal structure",
        "ONSET_METHOD": "adaptive_hp — handles ocean ambient noise",
    },
    "amphibian": {
        "HIGHPASS_CUTOFF_HZ": "300 Hz — frog calls are typically 300 Hz–5 kHz",
        "ONSET_AMPLITUDE_GATE": "0.05 — moderate gate for wetland environments",
        "ONSET_AMPLITUDE_WINDOW_MS": "40 ms — matches typical frog syllable length",
        "ONSET_SHARPNESS_GATE": "0.05 — light filter; frog calls can be tonal",
        "MIN_INTER_ONSET_MS": "20 ms — frogs can call in rapid bouts",
        "ONSET_CLUSTER_WINDOW_MS": "20 ms — moderate clustering for chorus recordings",
        "STABLE_RHYTHM_TOLERANCE": "0.25 — standard tolerance",
        "ONSET_DELTA": "0.06 — balanced sensitivity",
        "ONSET_METHOD": "adaptive_hp — handles wetland ambient noise",
    },
    "general / mixed": {
        "HIGHPASS_CUTOFF_HZ": "200 Hz — safe general-purpose cutoff",
        "ONSET_AMPLITUDE_GATE": "0.05 — balanced default",
        "ONSET_AMPLITUDE_WINDOW_MS": "50 ms — standard window",
        "ONSET_SHARPNESS_GATE": "0.05 — light sharpness filter",
        "MIN_INTER_ONSET_MS": "25 ms — accommodates most event rates",
        "ONSET_CLUSTER_WINDOW_MS": "20 ms — moderate clustering",
        "STABLE_RHYTHM_TOLERANCE": "0.25 — standard tolerance",
        "ONSET_DELTA": "0.06 — balanced sensitivity",
        "ONSET_METHOD": "adaptive_hp — most robust general-purpose method",
    },
    "ensemble": {
        "HIGHPASS_CUTOFF_HZ": "60 Hz — preserves deep bass drums and body percussion",
        "ONSET_AMPLITUDE_GATE": "0.02 — very permissive; catches quiet players in the back",
        "ONSET_AMPLITUDE_WINDOW_MS": "30 ms — short window resolves near-simultaneous hits",
        "ONSET_SHARPNESS_GATE": "0.0 — disabled; vocalisations and drums have different attack profiles",
        "MIN_INTER_ONSET_MS": "5 ms — near-zero; separate beats from different people can be <10 ms apart",
        "ONSET_CLUSTER_WINDOW_MS": "0 ms — disabled; every detected transient is kept as a separate onset",
        "STABLE_RHYTHM_TOLERANCE": "0.35 — lenient; group synchrony is looser than solo performance",
        "ONSET_DELTA": "0.04 — sensitive; dense textures require catching subtle transients",
        "ONSET_HOP_LENGTH": "128 — finer resolution (~2.9 ms at 44.1 kHz) for crowded onsets",
        "ONSET_METHOD": "adaptive_hp — handles varying dynamics across multiple performers",
    },
    "percussion_sharp_rawAudio": {
        "HIGHPASS_CUTOFF_HZ": "80 Hz — preserves stone impact body; cuts low rumble",
        "ONSET_AMPLITUDE_GATE": "0.08 — higher than default; rejects quiet speech/laugh triggers on raw audio",
        "ONSET_SHARPNESS_GATE": "0.15 — rejects soft/gradual onsets (laughter, singing); stone hits are very sharp",
        "MIN_INTER_ONSET_MS": "10 ms — near-minimum; allows separating closely-spaced hits from multiple people",
        "ONSET_CLUSTER_WINDOW_MS": "10 ms — much tighter than default; preserves closely-spaced hits",
        "STABLE_RHYTHM_TOLERANCE": "0.30 — slightly permissive for multi-person ensemble",
        "ONSET_DELTA": "0.07 — balanced; stone impacts have clear spectral flux",
        "ONSET_HOP_LENGTH": "128 — fine resolution (~2.9 ms) for separating close beats",
        "ONSET_REFINE_WINDOW_MS": "5 ms — tight; stone impacts have very defined peaks",
        "ONSET_METHOD": "adaptive_hp — best for percussive transients in noisy backgrounds",
        "APPLY_HIGHPASS_FILTER": "On — enabled because Audio Editor was skipped",
        "HP_SMOOTH_LAMBDA": "100 — smoother baseline helps ignore sustained singing/talking",
        "HP_THRESHOLD_LAMBDA": "1e8 — strict to suppress speech/laugh transients",
        "HP_ENVELOPE_WINDOW_MS": "5 ms — short; stone impacts are extremely brief",
    },
    "percussion_sharp_cleanedAudio": {
        "HIGHPASS_CUTOFF_HZ": "80 Hz — preserves stone impact resonance",
        "ONSET_AMPLITUDE_GATE": "0.03 — low gate; HPSS already removed most noise",
        "ONSET_SHARPNESS_GATE": "0.05 — light gate; cleaned audio has mostly genuine transients",
        "MIN_INTER_ONSET_MS": "10 ms — near-minimum; allows separating closely-spaced hits",
        "ONSET_CLUSTER_WINDOW_MS": "8 ms — very tight; maximally preserves near-simultaneous hits",
        "STABLE_RHYTHM_TOLERANCE": "0.30 — permissive for multi-person ensemble",
        "ONSET_DELTA": "0.07 — balanced for clean percussive audio",
        "ONSET_HOP_LENGTH": "128 — fine resolution for close-beat separation",
        "ONSET_REFINE_WINDOW_MS": "5 ms — tight; hits are well-defined after HPSS",
        "ONSET_METHOD": "adaptive_hp — most robust for percussive transients",
        "APPLY_HIGHPASS_FILTER": "Off — Audio Editor already filtered",
        "HP_SMOOTH_LAMBDA": "50 — default; less noise to contend with after cleaning",
        "HP_THRESHOLD_LAMBDA": "5e7 — default is fine on cleaned audio",
        "HP_ENVELOPE_WINDOW_MS": "5 ms — tight for brief stone impacts",
    },
    "percussion_sharp_rawAudio_2": {
        "HIGHPASS_CUTOFF_HZ": "60 Hz — lower cutoff to preserve quiet distant impacts that lose high-freq energy over distance",
        "ONSET_AMPLITUDE_GATE": "0.03 — much lower; distant hits are quiet and easily missed at higher gates",
        "ONSET_AMPLITUDE_WINDOW_MS": "30 ms — shorter window catches brief distant impacts better",
        "ONSET_SHARPNESS_GATE": "0.05 — low; distant hits lose their sharp edge so can't gate aggressively",
        "ONSET_SHARPNESS_WINDOW_MS": "15 ms — shorter window for finer transient discrimination",
        "MIN_INTER_ONSET_MS": "5 ms — near-minimum; hits can be just a few ms apart",
        "ONSET_CLUSTER_WINDOW_MS": "0 ms — disabled; never merge hits, even extremely close ones",
        "STABLE_RHYTHM_TOLERANCE": "0.35 — lenient; distant mic captures irregular timing",
        "ONSET_DELTA": "0.04 — very sensitive; quiet distant hits produce small spectral flux",
        "ONSET_HOP_LENGTH": "64 — ultra-fine resolution (~1.5 ms at 44.1 kHz) for ms-apart hits",
        "ONSET_REFINE_WINDOW_MS": "3 ms — very tight; maximise temporal precision for close hits",
        "ONSET_METHOD": "adaptive_hp — best for noisy backgrounds",
        "APPLY_HIGHPASS_FILTER": "On — needed since Audio Editor was skipped",
        "CLUSTER_OVERLAPPING_ONSETS": "Off — disabled so no closely-spaced hits are merged",
        "HP_SMOOTH_LAMBDA": "50 — moderate; lower than _1 so quiet transients aren't smoothed out",
        "HP_THRESHOLD_LAMBDA": "1e7 — much less strict than _1; distant hits are quiet and need lower threshold",
        "HP_ENVELOPE_WINDOW_MS": "3 ms — very short to capture brief, quiet impacts",
    },
    "percussion_sharp_cleanedAudio_2": {
        "HIGHPASS_CUTOFF_HZ": "60 Hz — preserves distant impact resonance (weaker than close-range)",
        "ONSET_AMPLITUDE_GATE": "0.01 — very low; distant hits are still quiet even after cleaning",
        "ONSET_AMPLITUDE_WINDOW_MS": "25 ms — short window for maximum sensitivity to brief events",
        "ONSET_SHARPNESS_GATE": "0.02 — nearly disabled; distant hits have diffuse transients even after HPSS",
        "ONSET_SHARPNESS_WINDOW_MS": "15 ms — shorter for finer transient resolution",
        "MIN_INTER_ONSET_MS": "5 ms — near-minimum; preserves very rapid hit sequences",
        "ONSET_CLUSTER_WINDOW_MS": "0 ms — disabled; every hit kept individually",
        "STABLE_RHYTHM_TOLERANCE": "0.35 — lenient for distant ensemble",
        "ONSET_DELTA": "0.03 — maximum sensitivity; cleaned audio should have low noise floor",
        "ONSET_HOP_LENGTH": "64 — ultra-fine resolution for ms-apart hits",
        "ONSET_REFINE_WINDOW_MS": "3 ms — very tight for maximum precision",
        "ONSET_METHOD": "adaptive_hp — most robust for percussive transients",
        "APPLY_HIGHPASS_FILTER": "Off — Audio Editor already filtered",
        "CLUSTER_OVERLAPPING_ONSETS": "Off — disabled so no closely-spaced hits are merged",
        "HP_SMOOTH_LAMBDA": "30 — less smoothing; quiet transients must not be averaged away",
        "HP_THRESHOLD_LAMBDA": "1e7 — relaxed; distant hits produce small threshold peaks",
        "HP_ENVELOPE_WINDOW_MS": "3 ms — very short for brief distant impacts",
    },
}


# ---------------------------------------------------------------------------
# Preset definitions — Audio Editor (Step 1)
# ---------------------------------------------------------------------------
MUTER_PRESETS = {
    "birdsong": {
        "description": "High-frequency bird calls in outdoor environments",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 500,
        "MUTER_LOWPASS_HZ": 12000,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 1000,
        "MUTER_BOOST_HIGH_HZ": 8000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "harmonic",
        "MUTER_HPSS_MARGIN": 2.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.5,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": False,
        "MUTER_COMPRESS_RATIO": 3.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": False,
        "MUTER_SHARPEN_GAIN_DB": 6,
        "MUTER_SHARPEN_ATTACK_MS": 15,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 5.0,
        "MUTER_NORMALIZE": None,
        "MUTER_NORMALIZE_TARGET_DB": -1.0,
        "MUTER_TRIM_SILENCE": False,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "percussion_sharp_noisyEnvir": {
        "description": "Sharp percussive hits in noisy environments — e.g. stone pounding, sakau ceremony. Aggressive HPSS + denoising to isolate transients from singing, speech, and crowd noise.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 80,
        "MUTER_LOWPASS_HZ": 6000,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 300,
        "MUTER_BOOST_HIGH_HZ": 3000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "percussive",
        "MUTER_HPSS_MARGIN": 3.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.5,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": False,
        "MUTER_COMPRESS_RATIO": 3.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": True,
        "MUTER_SHARPEN_GAIN_DB": 6,
        "MUTER_SHARPEN_ATTACK_MS": 10,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 4.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 3.0,
        "MUTER_NORMALIZE": "peak",
        "MUTER_NORMALIZE_TARGET_DB": -1.0,
        "MUTER_TRIM_SILENCE": False,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "percussion_sharp_noisyEnvir_2": {
        "description": "Distant sharp percussive hits in noisy environments — performers far from mic, quieter hits buried in crowd noise. Gentler HPSS/denoising to preserve quiet transients, compression to bring up distant hits, stronger transient sharpening.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 60,
        "MUTER_LOWPASS_HZ": 8000,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 300,
        "MUTER_BOOST_HIGH_HZ": 3000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "percussive",
        "MUTER_HPSS_MARGIN": 2.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.0,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": True,
        "MUTER_COMPRESS_RATIO": 3.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -35,
        "MUTER_SHARPEN_TRANSIENTS": True,
        "MUTER_SHARPEN_GAIN_DB": 8,
        "MUTER_SHARPEN_ATTACK_MS": 5,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 3.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 2.0,
        "MUTER_NORMALIZE": "peak",
        "MUTER_NORMALIZE_TARGET_DB": -1.0,
        "MUTER_TRIM_SILENCE": False,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "ensemble": {
        "description": "Group performance — drumming circles, choruses, multiple simultaneous sources",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 60,
        "MUTER_LOWPASS_HZ": 0,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 300,
        "MUTER_BOOST_HIGH_HZ": 3000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "percussive",
        "MUTER_HPSS_MARGIN": 2.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.0,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": True,
        "MUTER_COMPRESS_RATIO": 2.5,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": True,
        "MUTER_SHARPEN_GAIN_DB": 4,
        "MUTER_SHARPEN_ATTACK_MS": 8,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 3.0,
        "MUTER_NORMALIZE": "peak",
        "MUTER_NORMALIZE_TARGET_DB": -1.0,
        "MUTER_TRIM_SILENCE": True,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "music_vocal_isolation": {
        "description": "Human song — isolate singing voice for syllable/word rhythm analysis. Best used after Demucs vocal-stem separation. Emphasises vocal formant range (80–4000 Hz), gentle compression to level soft/loud passages.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 80,
        "MUTER_LOWPASS_HZ": 4000,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.97,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 300,
        "MUTER_BOOST_HIGH_HZ": 3000,
        "MUTER_BOOST_GAIN_DB": 4.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "harmonic",
        "MUTER_HPSS_MARGIN": 2.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.2,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": True,
        "MUTER_COMPRESS_RATIO": 2.5,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": False,
        "MUTER_SHARPEN_GAIN_DB": 6,
        "MUTER_SHARPEN_ATTACK_MS": 15,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 5.0,
        "MUTER_NORMALIZE": "rms",
        "MUTER_NORMALIZE_TARGET_DB": -18.0,
        "MUTER_TRIM_SILENCE": True,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "music_drums_isolation": {
        "description": "Human song — isolate drums/percussion for beat-level rhythm analysis. Best used after Demucs drums-stem separation. Hard HPSS percussive split, aggressive transient sharpening to make onsets pop.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 40,
        "MUTER_LOWPASS_HZ": 0,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 60,
        "MUTER_BOOST_HIGH_HZ": 5000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "percussive",
        "MUTER_HPSS_MARGIN": 3.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.5,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": False,
        "MUTER_COMPRESS_RATIO": 3.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": True,
        "MUTER_SHARPEN_GAIN_DB": 9,
        "MUTER_SHARPEN_ATTACK_MS": 10,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 3.0,
        "MUTER_NORMALIZE": "peak",
        "MUTER_NORMALIZE_TARGET_DB": -1.0,
        "MUTER_TRIM_SILENCE": True,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "music_full_mix": {
        "description": "Human song — full mix (no source separation). Uses minimal processing to preserve the original mix. Best paired with per_band onset detection which naturally separates frequency ranges.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 30,
        "MUTER_LOWPASS_HZ": 0,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.0,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 200,
        "MUTER_BOOST_HIGH_HZ": 5000,
        "MUTER_BOOST_GAIN_DB": 6.0,
        "MUTER_HPSS_ENABLED": False,
        "MUTER_HPSS_TARGET": "percussive",
        "MUTER_HPSS_MARGIN": 2.0,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.0,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": True,
        "MUTER_COMPRESS_RATIO": 2.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -25,
        "MUTER_SHARPEN_TRANSIENTS": False,
        "MUTER_SHARPEN_GAIN_DB": 6,
        "MUTER_SHARPEN_ATTACK_MS": 15,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 5.0,
        "MUTER_NORMALIZE": "rms",
        "MUTER_NORMALIZE_TARGET_DB": -16.0,
        "MUTER_TRIM_SILENCE": False,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
    "music_group_singing": {
        "description": "Group/choral singing — multiple voices, possibly with hand-claps or body percussion. Compression levels all singers, HPSS harmonic keeps sustained vocal content, gentle denoising for ambient room/outdoor noise.",
        "MUTER_CHANNEL": "mix",
        "MUTER_RESAMPLE_HZ": 44100,
        "MUTER_HIGHPASS_HZ": 80,
        "MUTER_LOWPASS_HZ": 6000,
        "MUTER_NOTCH_FREQS": [],
        "MUTER_NOTCH_Q": 30,
        "MUTER_PRE_EMPHASIS": 0.97,
        "MUTER_BANDPASS_BOOST": False,
        "MUTER_BOOST_LOW_HZ": 200,
        "MUTER_BOOST_HIGH_HZ": 4000,
        "MUTER_BOOST_GAIN_DB": 4.0,
        "MUTER_HPSS_ENABLED": True,
        "MUTER_HPSS_TARGET": "harmonic",
        "MUTER_HPSS_MARGIN": 1.5,
        "MUTER_HPSS_EMPHASIS_DB": 0,
        "MUTER_SPECTRAL_DENOISE": True,
        "MUTER_DENOISE_STRENGTH": 1.0,
        "MUTER_SPECTRAL_ENHANCE": False,
        "MUTER_ENHANCE_FACTOR": 2.0,
        "MUTER_COMPRESS": True,
        "MUTER_COMPRESS_RATIO": 3.0,
        "MUTER_COMPRESS_THRESHOLD_DB": -30,
        "MUTER_SHARPEN_TRANSIENTS": False,
        "MUTER_SHARPEN_GAIN_DB": 6,
        "MUTER_SHARPEN_ATTACK_MS": 15,
        "MUTER_AUTO_THRESHOLD": True,
        "MUTER_NOISE_MARGIN_DB": 6.0,
        "MUTER_DB_THRESHOLD": 30,
        "MUTER_FADE_MS": 5.0,
        "MUTER_NORMALIZE": "rms",
        "MUTER_NORMALIZE_TARGET_DB": -18.0,
        "MUTER_TRIM_SILENCE": True,
        "MUTER_TRIM_THRESHOLD_DB": 40,
    },
}


# Audio Editor preset reasons — explains *why* each setting was changed
_MUTER_PRESET_REASONS = {
    "birdsong": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate ensures consistent FFT bins across recordings",
        "MUTER_HIGHPASS_HZ": "500 Hz — bird songs sit above this; aggressively removes wind/traffic",
        "MUTER_LOWPASS_HZ": "12000 Hz — caps ultrasonic interference while keeping all birdsong harmonics",
        "MUTER_HPSS_ENABLED": "On — separates sustained bird calls from percussive background noise",
        "MUTER_HPSS_TARGET": "Harmonic — bird songs are tonal, sustained vocalisations",
        "MUTER_HPSS_MARGIN": "2.0 — moderate separation keeps most call energy intact",
        "MUTER_SPECTRAL_DENOISE": "On — removes persistent insect/wind hiss common in field recordings",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate; preserves call harmonics while removing hiss",
        "MUTER_NOISE_MARGIN_DB": "8 dB — slightly permissive; preserves quiet distant calls",
        "MUTER_NORMALIZE": "Peak — standardises volume so quiet & loud recordings can be compared",
    },
    "percussion_clean": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate for consistent timing precision",
        "MUTER_HIGHPASS_HZ": "80 Hz — preserves bass drum and low tom frequencies",
        "MUTER_HPSS_ENABLED": "Off — clean recording doesn't need source separation",
        "MUTER_SPECTRAL_DENOISE": "Off — clean recording has minimal background noise",
        "MUTER_AUTO_THRESHOLD": "On — silences noise-floor regions to prevent false onset detections",
        "MUTER_NOISE_MARGIN_DB": "10 dB — generous margin keeps quiet hits audible; only true silence is muted",
        "MUTER_FADE_MS": "5 ms — smooth transitions prevent mute edges from triggering onsets",
        "MUTER_NORMALIZE": "Peak — ensures all recordings hit the same maximum without clipping",
        "MUTER_TRIM_SILENCE": "On — removes dead silence at the start/end of performance recordings",
    },
    "percussion_messy": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate for consistent timing precision",
        "MUTER_HIGHPASS_HZ": "80 Hz — preserves bass drum and low tom frequencies",
        "MUTER_HPSS_ENABLED": "On — isolates sharp hits from room ambience and tonal bleed",
        "MUTER_HPSS_TARGET": "Percussive — keeps sharp transients, removes sustained tones",
        "MUTER_HPSS_MARGIN": "3.0 — hard split for clean transient isolation",
        "MUTER_SPECTRAL_DENOISE": "On — removes room tone, air conditioning, audience noise",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate; avoids smearing drum transients",
        "MUTER_NOISE_MARGIN_DB": "6 dB — balanced default; drum hits are loud and clear",
        "MUTER_SHARPEN_TRANSIENTS": "On — sharpens the attack of each hit for crisper onset detection",
        "MUTER_SHARPEN_ATTACK_MS": "10 ms — short window targets the initial stick/hand impact",
        "MUTER_NORMALIZE": "Peak — ensures all recordings hit the same maximum without clipping",
        "MUTER_TRIM_SILENCE": "On — removes dead silence at the start/end of performance recordings",
    },
    "primate": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — unifies varied field recorder sample rates",
        "MUTER_HIGHPASS_HZ": "150 Hz — preserves low-frequency buttress drumming and pant-hoot fundamentals",
        "MUTER_PRE_EMPHASIS": "0.97 — compensates for high-frequency roll-off due to recording distance in forest",
        "MUTER_HPSS_ENABLED": "On — separates drumming transients from forest ambience",
        "MUTER_HPSS_TARGET": "Percussive — targets buttress-drumming hits and sharp calls",
        "MUTER_HPSS_MARGIN": "2.5 — moderate; forest reverb blurs harmonic/percussive boundary",
        "MUTER_SPECTRAL_DENOISE": "On — tropical forests have constant insect and river noise",
        "MUTER_DENOISE_STRENGTH": "2.0 — aggressive; tropical field recordings are very noisy",
        "MUTER_COMPRESS": "On — boosts distant drumming closer to the volume of nearby hits",
        "MUTER_COMPRESS_THRESHOLD_DB": "-35 dBFS — lower threshold catches faint distant drumming events",
        "MUTER_SHARPEN_TRANSIENTS": "On — sharpens buttress-drumming impacts that are softened by distance",
        "MUTER_NOISE_MARGIN_DB": "8 dB — permissive; distant drumming can be quiet",
        "MUTER_NORMALIZE": "RMS — matches perceived loudness across recordings at varying distances",
        "MUTER_NORMALIZE_TARGET_DB": "-3.0 dBFS — conservative headroom for dynamic forest recordings",
    },
    "insect": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate; most insect content is well below Nyquist",
        "MUTER_HIGHPASS_HZ": "1000 Hz — insect sounds are typically 1 kHz and above",
        "MUTER_HPSS_ENABLED": "Off — insect sounds don't split cleanly into harmonic/percussive",
        "MUTER_BANDPASS_BOOST": "On — amplifies the 2–12 kHz band where most insect stridulations sit",
        "MUTER_BOOST_LOW_HZ": "2000 Hz — lower edge of the typical insect vocalisation band",
        "MUTER_BOOST_HIGH_HZ": "12000 Hz — upper edge captures high-frequency stridulation harmonics",
        "MUTER_BOOST_GAIN_DB": "4 dB — gentle boost; avoids amplifying noise alongside signal",
        "MUTER_SPECTRAL_DENOISE": "On — removes low-frequency ambient hum and wind",
        "MUTER_DENOISE_STRENGTH": "2.0 — aggressive; insect recordings tend to be very noisy",
        "MUTER_SPECTRAL_ENHANCE": "On — amplifies insect sounds that stand out above the noise floor",
        "MUTER_ENHANCE_FACTOR": "2.5 — moderately strong; insect signals are often faint",
        "MUTER_NOISE_MARGIN_DB": "4 dB — tight margin; insect signals can be close to the noise floor",
        "MUTER_DB_THRESHOLD": "25 dB — lower than default; catches quiet stridulations",
        "MUTER_FADE_MS": "3 ms — shorter crossfade for rapid click trains",
        "MUTER_NORMALIZE": "Peak — standardises volume across recordings of varying quality",
    },
    "whale / marine mammal": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — unifies hydrophone rates (often 48000 or 96000)",
        "MUTER_HIGHPASS_HZ": "20 Hz — whale infrasonic content extends below human hearing",
        "MUTER_LOWPASS_HZ": "2000 Hz — removes high-frequency snapping-shrimp and boat noise",
        "MUTER_BANDPASS_BOOST": "On — amplifies 30–1500 Hz where most whale vocalisations occur",
        "MUTER_BOOST_LOW_HZ": "30 Hz — captures infrasonic blue/fin whale calls",
        "MUTER_BOOST_HIGH_HZ": "1500 Hz — includes humpback song and dolphin whistles",
        "MUTER_BOOST_GAIN_DB": "4 dB — gentle; whale calls are easily distorted by over-boosting",
        "MUTER_HPSS_ENABLED": "On — separates tonal whale song from percussive snapping shrimp",
        "MUTER_HPSS_TARGET": "Harmonic — whale calls are long, frequency-swept tonal signals",
        "MUTER_HPSS_MARGIN": "2.0 — moderate; underwater acoustics are complex",
        "MUTER_HPSS_EMPHASIS_DB": "6 dB — emphasis mode keeps full underwater soundscape while highlighting calls",
        "MUTER_SPECTRAL_DENOISE": "On — removes constant ocean ambient noise (wave action, ships)",
        "MUTER_DENOISE_STRENGTH": "1.0 — conservative; whale calls can be faint and easily damaged",
        "MUTER_COMPRESS": "On — boosts faint, distant whale calls closer to loud nearby ones",
        "MUTER_COMPRESS_RATIO": "2.0 — gentle; preserves natural amplitude envelope of whale song",
        "MUTER_COMPRESS_THRESHOLD_DB": "-40 dBFS — very low; catches faint whale calls near the noise floor",
        "MUTER_NOISE_MARGIN_DB": "10 dB — very permissive; distant whale calls are barely above noise",
        "MUTER_FADE_MS": "10 ms — longer crossfade suits the slow temporal structure of whale calls",
        "MUTER_NORMALIZE": "RMS — matches perceived loudness across recordings from different distances",
        "MUTER_NORMALIZE_TARGET_DB": "-3.0 dBFS — conservative headroom for highly dynamic underwater recordings",
    },
    "amphibian": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate for consistent analysis",
        "MUTER_HIGHPASS_HZ": "300 Hz — frog calls are typically 300 Hz–5 kHz",
        "MUTER_LOWPASS_HZ": "6000 Hz — caps above frog vocal range; reduces insect interference",
        "MUTER_HPSS_ENABLED": "Off — frog calls don't benefit much from HPSS",
        "MUTER_SPECTRAL_DENOISE": "On — removes water, wind, and insect background",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate; preserves call harmonics",
        "MUTER_NOISE_MARGIN_DB": "6 dB — balanced default for wetland environments",
    },
    "general / mixed": {
        "MUTER_HIGHPASS_HZ": "200 Hz — safe general-purpose cutoff",
        "MUTER_HPSS_ENABLED": "Off — disabled by default; enable if needed for your data",
        "MUTER_SPECTRAL_DENOISE": "On — generally beneficial for any field recording",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate balanced default",
        "MUTER_NOISE_MARGIN_DB": "6 dB — balanced default",
    },
    "percussion_sharp_noisyEnvir": {
        "MUTER_HIGHPASS_HZ": "80 Hz — removes low rumble but preserves stone impact body",
        "MUTER_LOWPASS_HZ": "6000 Hz — cuts high-freq hiss and crowd sibilance; keeps stone crack transients",
        "MUTER_HPSS_ENABLED": "On — critical for separating sustained singing from percussive stone hits",
        "MUTER_HPSS_TARGET": "Percussive — isolates sharp stone impacts; removes sustained singing/speech",
        "MUTER_HPSS_MARGIN": "3.0 — aggressive separation to really strip out singing and talking",
        "MUTER_SPECTRAL_DENOISE": "On — suppresses persistent tonal background (singing, ambient noise)",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate; avoids smearing the stone transients",
        "MUTER_SHARPEN_TRANSIENTS": "On — makes stone hit attacks even more defined for onset detection",
        "MUTER_SHARPEN_GAIN_DB": "6 dB — moderate boost to attack edges",
        "MUTER_SHARPEN_ATTACK_MS": "10 ms — stone impacts are very brief; tight window",
        "MUTER_NOISE_MARGIN_DB": "4 dB — aggressive muting; lots of background noise to suppress",
        "MUTER_FADE_MS": "3 ms — short crossfade; don't blur nearby transients",
        "MUTER_NORMALIZE": "Peak — consistent output level",
    },
    "percussion_sharp_noisyEnvir_2": {
        "MUTER_HIGHPASS_HZ": "60 Hz — lower than _1; preserves more body of distant impacts",
        "MUTER_LOWPASS_HZ": "8000 Hz — wider than _1; distant hits lose high-freq, so keep more bandwidth",
        "MUTER_HPSS_ENABLED": "On — still needed for separating singing from stone hits",
        "MUTER_HPSS_TARGET": "Percussive — isolates stone hits from sustained sounds",
        "MUTER_HPSS_MARGIN": "2.0 — gentler than _1 (3.0); aggressive HPSS strips quiet distant hits",
        "MUTER_SPECTRAL_DENOISE": "On — removes persistent background noise",
        "MUTER_DENOISE_STRENGTH": "1.0 — gentler than _1 (1.5); avoids erasing quiet distant transients",
        "MUTER_COMPRESS": "On — brings up quiet distant hits closer to louder nearby sounds",
        "MUTER_COMPRESS_RATIO": "3.0 — moderate compression to level out near/far hit volumes",
        "MUTER_COMPRESS_THRESHOLD_DB": "-35 dBFS — low threshold catches quiet distant impacts",
        "MUTER_SHARPEN_TRANSIENTS": "On — sharpens diffuse distant transients to aid onset detection",
        "MUTER_SHARPEN_GAIN_DB": "8 dB — stronger than _1 (6 dB); distant hits need more boost",
        "MUTER_SHARPEN_ATTACK_MS": "5 ms — tighter than _1 (10 ms); concentrate boost on impact moment",
        "MUTER_NOISE_MARGIN_DB": "3 dB — less aggressive than _1 (4 dB); don't mute quiet distant hits",
        "MUTER_FADE_MS": "2 ms — very short; minimise any blurring of closely-spaced hits",
        "MUTER_NORMALIZE": "Peak — consistent output level",
    },
    "ensemble": {
        "MUTER_RESAMPLE_HZ": "44100 Hz — standard rate for consistent onset timing",
        "MUTER_HIGHPASS_HZ": "60 Hz — preserves deep bass drums; removes sub-bass rumble",
        "MUTER_HPSS_ENABLED": "On — separates percussive transients from tonal voice content",
        "MUTER_HPSS_TARGET": "Percussive — isolates sharp hits from overlapping vocalisations",
        "MUTER_HPSS_MARGIN": "2.0 — moderate separation; keeps both drum and hand-clap transients",
        "MUTER_SPECTRAL_DENOISE": "On — removes crowd/room noise between beats",
        "MUTER_DENOISE_STRENGTH": "1.0 — gentle; dense group audio is easily over-denoised",
        "MUTER_COMPRESS": "On — evens out loud (front) and quiet (back) performers",
        "MUTER_COMPRESS_RATIO": "2.5 — moderate; don’t flatten all dynamics",
        "MUTER_SHARPEN_TRANSIENTS": "On — sharpens overlapping hits for better discrimination",
        "MUTER_SHARPEN_GAIN_DB": "4 dB — gentle boost to attack portion",
        "MUTER_SHARPEN_ATTACK_MS": "8 ms — very short; targets just the initial impact",
        "MUTER_FADE_MS": "3 ms — short crossfade preserves timing of closely-spaced hits",
        "MUTER_NORMALIZE": "Peak — standardises volume for consistent onset thresholds",
        "MUTER_TRIM_SILENCE": "On — removes dead air before/after performance",
    },
    "music_vocal_isolation": {
        "MUTER_HIGHPASS_HZ": "80 Hz — preserves full vocal fundamental; removes sub-bass rumble",
        "MUTER_LOWPASS_HZ": "4000 Hz — caps above vocal formants; removes cymbal/instrument bleed",
        "MUTER_PRE_EMPHASIS": "0.97 — standard pre-emphasis for voice; boosts consonant clarity",
        "MUTER_HPSS_ENABLED": "On — separates sustained vocal harmonics from percussive bleed",
        "MUTER_HPSS_TARGET": "Harmonic — keeps the sustained singing content",
        "MUTER_SPECTRAL_DENOISE": "On — removes residual instrument/room noise",
        "MUTER_DENOISE_STRENGTH": "1.2 — moderate; avoids artefacts on vocal formants",
        "MUTER_COMPRESS": "On — evens out dynamic singing (quiet verses, loud choruses)",
        "MUTER_COMPRESS_RATIO": "2.5 — gentle compression preserves natural expression",
        "MUTER_NORMALIZE": "RMS — matches perceived loudness across different songs",
        "MUTER_NORMALIZE_TARGET_DB": "-18 dBFS — broadcast loudness standard for speech/voice",
        "MUTER_TRIM_SILENCE": "On — removes silent intro/outro for cleaner rhythm analysis",
    },
    "music_drums_isolation": {
        "MUTER_HIGHPASS_HZ": "40 Hz — preserves kick drum fundamentals; removes sub-bass",
        "MUTER_HPSS_ENABLED": "On — separates sharp drum transients from residual tonal bleed",
        "MUTER_HPSS_TARGET": "Percussive — isolates sharp attacks (drums, claps, impacts)",
        "MUTER_HPSS_MARGIN": "3.0 — hard split; aggressively reject sustained instrument tones",
        "MUTER_SPECTRAL_DENOISE": "On — removes residual vocal/instrument noise between hits",
        "MUTER_DENOISE_STRENGTH": "1.5 — moderate-strong; drum stems tolerate more aggressive denoising",
        "MUTER_SHARPEN_TRANSIENTS": "On — boost drum attacks for sharper onset detection",
        "MUTER_SHARPEN_GAIN_DB": "9 dB — strong boost; makes each hit pop clearly above the noise",
        "MUTER_SHARPEN_ATTACK_MS": "10 ms — short attack window targets just the initial drum impact",
        "MUTER_FADE_MS": "3 ms — short crossfade preserves closely-spaced hits (rolls, fills)",
        "MUTER_NORMALIZE": "Peak — preserves relative loudness between strong/weak hits",
    },
    "music_full_mix": {
        "MUTER_HIGHPASS_HZ": "30 Hz — minimal filtering; preserves bass and sub-bass content",
        "MUTER_HPSS_ENABLED": "Off — don't separate; per_band onset detection handles polyphony",
        "MUTER_SPECTRAL_DENOISE": "On — removes background hiss/room noise",
        "MUTER_DENOISE_STRENGTH": "1.0 — gentle; avoid distorting the dense mix",
        "MUTER_COMPRESS": "On — levels out dynamic range for consistent onset detection",
        "MUTER_COMPRESS_RATIO": "2.0 — gentle; preserves musical dynamics",
        "MUTER_COMPRESS_THRESHOLD_DB": "-25 dBFS — catches moderately quiet passages",
        "MUTER_NORMALIZE": "RMS — matches perceived loudness across songs of different genres",
        "MUTER_NORMALIZE_TARGET_DB": "-16 dBFS — slightly louder target for dense mixes",
    },
    "music_group_singing": {
        "MUTER_HIGHPASS_HZ": "80 Hz — preserves deep male voices; removes rumble",
        "MUTER_LOWPASS_HZ": "6000 Hz — caps above vocal range; removes high-freq instrument bleed",
        "MUTER_PRE_EMPHASIS": "0.97 — standard pre-emphasis; sharpens syllable articulation",
        "MUTER_HPSS_ENABLED": "On — separates sustained vocal harmonics from body percussion",
        "MUTER_HPSS_TARGET": "Harmonic — preserves singing; removes hand-claps/stomps",
        "MUTER_HPSS_MARGIN": "1.5 — soft split; some bleed is fine for natural group singing",
        "MUTER_SPECTRAL_DENOISE": "On — removes ambient room/outdoor noise between phrases",
        "MUTER_DENOISE_STRENGTH": "1.0 — gentle; dense choral audio is easily over-denoised",
        "MUTER_COMPRESS": "On — levels loud and quiet singers for uniform syllable detection",
        "MUTER_COMPRESS_RATIO": "3.0 — moderate compression; some singers much louder than others",
        "MUTER_NORMALIZE": "RMS — consistent perceived loudness across group recordings",
        "MUTER_TRIM_SILENCE": "On — removes dead air before/after the singing",
    },
}


__all__ = [
    "PRESETS",
    "_ONSET_PRESET_REASONS",
    "MUTER_PRESETS",
    "_MUTER_PRESET_REASONS",
]